# Generated by Django 4.1.6 on 2023-02-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersSubjects',
            new_name='TeachersSubject',
        ),
    ]
