# Generated by Django 4.1.6 on 2023-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_teacherssubjects_teacherssubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1),
        ),
    ]
