# Generated by Django 4.1.6 on 2023-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('ж', 'женский'), ('м', 'мужской')], max_length=1),
        ),
    ]
